// api-types.ts
//
// This file contains TypeScript interfaces for API responses and request bodies,
// mirroring the backend's OpenAPI specification.

/**
 * Interface for a Task as returned by the API.
 */
export interface Task {
  id: string; // UUID string
  user_id: string; // UUID string
  title: string;
  description: string | null;
  completed: boolean;
  created_at: string; // ISO 8601 date-time string
  updated_at: string; // ISO 8601 date-time string
}

/**
 * Interface for creating a new Task.
 * 'id', 'user_id', 'created_at', 'updated_at' are omitted as they are generated by the backend.
 */
export interface TaskCreate {
  title: string;
  description?: string | null; // Optional
  completed?: boolean; // Optional, defaults to false
}

/**
 * Interface for updating an existing Task.
 * All fields are optional for partial updates (PATCH/PUT).
 */
export interface TaskUpdate {
  title?: string;
  description?: string | null;
  completed?: boolean;
}

/**
 * Interface for API error responses.
 */
export interface ApiError {
  detail: string | Array<{ loc: string[]; msg: string; type: string }>;
}
